# Generated by Django 4.2.1 on 2023-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('#E26C2D', 'breakfast'), ('#49B64E', 'LUNCH'), ('#8775fD2', 'DINNER')], max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('#E26C2D', 'breakfast'), ('#49B64E', 'LUNCH'), ('#8775fD2', 'DINNER')], max_length=200, verbose_name='Название'),
        ),
    ]
