# Generated by Django 4.2.1 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_tag_colour_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('#E26C2D', 'orange'), ('#49B64E', 'green'), ('#8775fD2', 'purple')], max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=200, verbose_name='Название'),
        ),
    ]
