# Generated by Django 4.2.1 on 2023-06-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',)},
        ),
    ]
