# Generated by Django 4.2.1 on 2023-06-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('#E26C2D', 'orange'), ('#49B64E', 'green'), ('#8775fD2', 'purple')], max_length=200, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
