# Generated by Django 4.2.1 on 2023-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_ingridient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
