# Generated by Django 4.2.1 on 2023-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_ingridientforrecipe_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngridientForRecipe',
            new_name='IngredientForRecipe',
        ),
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='food.IngredientForRecipe', to='food.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
