# Generated by Django 4.2.1 on 2023-06-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
