# Generated by Django 4.2.1 on 2023-06-12 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0016_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favorites',
        ),
    ]
