# Generated by Django 4.2.1 on 2023-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
    ]
