# Generated by Django 4.2.1 on 2023-06-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follower_user_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
