# Generated by Django 4.2.1 on 2023-06-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_delete_follower_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.follow'),
            preserve_default=False,
        ),
    ]
