# Generated by Django 4.2.1 on 2023-06-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_tag_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='colour',
            new_name='color',
        ),
    ]
